App\Entity\Provincias:
  attributes:
    id:
      groups: ['post_direccion','get_direccion','patch_direccion','get_provincia']
    provincia:
      groups: ['post_direccion','get_direccion','patch_direccion','get_provincia']