App\Entity\Restaurante:
  attributes:
    id:
      groups: ['get_restaurante', 'filter_restaurante']
    nombre:
      groups: ['get_restaurante', 'filter_restaurante']
    logoUrl:
      groups: ['get_restaurante', 'filter_restaurante']
    imagenUrl:
      groups: ['get_restaurante']
    descripcion:
      groups: ['get_restaurante']
    destacado:
      groups: ['get_restaurante']
    platos:
      groups: ['get_restaurante']
    horarios:
      groups: ['get_restaurante']
    categorias:
      groups: ['get_restaurante', 'filter_restaurante']
    municipio:
      groups: ['get_restaurante']